---
title: 'Practical Mixed Models for Actuaries'
subtitle: 'Code Chuncks Extracted via AWK script'
author: 'Ernesto Schirmacher'
output: html_notebook
temporary: in review (to be deleted)
---

## Chapter 4--Linear Mixed Models

```{r}
#| include: false

library(tidyverse)
library(patchwork)
library(lme4)
library(mvtnorm)
```

```{r}
dta <- tibble(class = factor(rep(1:3, each = 4),
                             levels = 1:3),
              time = rep(1:4, times = 3),
              value = c(625, 675, 600, 700,
                        750, 800, 650, 800,
                        900, 700, 850, 950))
```

```{r}
BB.null.lm <- lm(value ~ 1,
                 data = dta)
(sBB.null.lm <- summary(BB.null.lm))
```

```{r}
#| echo: true

dta$res.null <- resid(BB.null.lm)
```

```{r}
#| label: fig-BB-null-ols-residuals
#| fig-cap: "Ordinary least squares residuals for the balanced B&uuml;hlmann example data. Note that the residuals for class #1 all have the same sign and nearly all points for class #3 also have the same sign. We introduced a slight amount of vertical jittering to avoid over plotting a pair of residuals."

ggplot(data = dta,
       mapping = aes(x = res.null,
                     y = class)) +
  geom_jitter(width = 0, height = 0.1) +
  labs(x = "Residuals",
       y = "Class")
```

```{r}
BB.class.lm <- lm(value ~ class - 1,
                  data = dta)
(sBB.class.lm <- summary(BB.class.lm))
```

```{r}
#| echo: true

dta$res.class <- resid(BB.class.lm)
```

```{r}
#| label: fig-BB-class-ols-residuals
#| fig-cap: "Ordinary least squares residuals for the balanced B&uuml;hlmann example data with a mean estimate for each class. Note that now all the residuals are centered around zero. We introduced a slight amount of vertical jittering to avoid over plotting a pair of residuals."

ggplot(data = dta,
       mapping = aes(x = res.class,
                     y = class)) +
  geom_jitter(width = 0, height = 0.2) +
  labs(x = "Residuals",
       y = "Class")
```

```{r}
BB.mx <- lmer(value ~ 1 + (1 | class),
              data = dta)
```

```{r}
(sBB.mx <- summary(BB.mx))
```

```{r}
round(ranef(BB.mx)$class, 3)
```

```{r}
dta$mu.mx <- fitted(BB.mx)
dta$sres.mx <- resid(BB.mx, type = "pearson", scaled = TRUE)
```

```{r}
#| label: fig-BB-mixed-standardized-residuals
#| fig-cap: "Standardized residuals for the balanced B&uuml;hlmann data fitted with the mixed model. Note that all residuals are within 1.5 standard deviations from zero.  We added a bit of horizontal jittering to avoid over plotting a pair of residuals."

ggplot(data = dta,
       mapping = aes(x = mu.mx,
                     y = sres.mx)) +
  geom_jitter(width = 3, height = 0) +
  labs(x = "Fitted Values",
       y = "Standardized Residuals")
```

```{r}
#| include: false

rm(list = c(ls(pattern = "s*BB"), "dta"))
```

```{r}
bs.dta <- read_csv("BS-simulated-data.csv",
                   col_types = "fdd")
```

```{r}
BS.mx <- lmer(X.jt ~ 1 + (1 | risk),
              data = bs.dta,
              weights = W.jt)
```

```{r}
(sBS.mx <- summary(BS.mx))
```

```{r}
round(ranef(BS.mx)$risk[1:20,1], 3)
```

```{r}
round(fixef(BS.mx) + ranef(BS.mx)$risk[1:20, 1], 3)
```

```{r}
bs.dta$mu.mx <- fitted(BS.mx)
bs.dta$sres.mx <- resid(BS.mx, type = "pearson", scaled = TRUE)
```

```{r}
#| label: fig-BS-FV-vs-SR
#| fig-cap: "Diagnostic plot for the linear mixed model with random intercepts fitted to the simulated B&uuml;hlmann-Straub data. All the standardized residuals are within 2.5 standard deviations from the origin. The overall impression is that of a random cloud of points."

ggplot(data = bs.dta,
       mapping = aes(x = mu.mx,
                     y = sres.mx)) +
  geom_point() + 
  labs(x = "Fitted Values",
       y = "Standardized Residuals")
```

```{r}
BS.lm <- lm(sres.mx ~ mu.mx,
            data = bs.dta)
(sBS.lm <- summary(BS.lm))
```

```{r}
#| message: false

ggplot(data = bs.dta,
       mapping = aes(x = mu.mx,
                     y = sres.mx)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Fitted Values",
       y = "Standardized Residuals")
```

```{r}
#| include: false

rsk <- bs.dta %>%
  group_by(risk) %>%
  summarize(W.jb = sum(W.jt),
            X.bar.j = sum(W.jt * X.jt) / sum(W.jt),
            mu.j = first(mu.mx))
rsk$mu.rnk <- rank(rsk$mu.j)
dtb <- left_join(bs.dta, rsk, by = "risk")
```

```{r}
#| label: fig-BS-shrinkage-effect
#| fig-cap: "The top-left panel shows the simulated B&uuml;hlmann-Straub data where the risk groups have been ordered from smallest fitted value to largest. The fitted values come from the linear mixed model and coincide with the credibility weighted values. The top-right panel shows the fitted values and the bottom-left panel shows the average response value for each risk group. The bottom-right panel combines all three panels.  Note that the fitted values have been shrunk towards the overall mean value of approximately 80."

p1 <- ggplot(data = dtb,
             mapping = aes(x = mu.rnk,
                           y = X.jt)) + 
  geom_point(color = "gray", pch = 1) + 
  labs(x = "Risk Group",
       y = "Response Value")

p2 <- p1 + geom_point(data = rsk,
                      mapping = aes(x = mu.rnk,
                                    y = X.bar.j),
                      color = "lightblue")

p3 <- p1 + geom_point(data = rsk,
                      mapping = aes(x = mu.rnk,
                                    y = mu.j),
                      color = "pink")

p4 <- p2 + geom_point(data = rsk,
                      mapping = aes(x = mu.rnk,
                                    y = mu.j),
                      color = "pink")

(p1 + p2) / (p3 + p4)
```

```{r}
#| include: false

rm(list = ls(pattern = "s*[Bb][Ss]"))
rm(list = ls(pattern = "p+"))
rm(rsk, dtb)
```

```{r}
hm.dta <- read_csv("hachemeister-data.csv",
                   col_types = "fidd")
```

```{r}
hm.mixed.1 <- lmer(severity ~ time + (time | state),
                   data = hm.dta,
                   weights = claims/1000)
```

```{r}
summary(hm.mixed.1)
```

```{r}
print(VarCorr(hm.mixed.1), comp = "Variance")
```

```{r}
eigen(VarCorr(hm.mixed.1)$state)$value
```

```{r}
hm.mixed.2 <- lmer(severity ~ time + (1 | state) + (0 + time | state),
                   data = hm.dta,
                   weights = claims/1000)
summary(hm.mixed.2)
```

```{r}
ranef(hm.mixed.2)$state
```
and putting these together with the fixed effects we obtain the
following credibility weighted values:

```{r}
round(fixef(hm.mixed.2) + t(as.matrix(ranef(hm.mixed.2)$state)), 2)
```

```{r}
CG <- with(hm.dta,
           tapply(time * claims, state, sum) /
             tapply(claims, state, sum))
hm.dta$ctime <- hm.dta$time - CG[hm.dta$state]
rm(CG)
```

```{r}
hm.mixed.3 <- lmer(severity ~ ctime + (1 | state) + (0 + ctime | state),
                   data = hm.dta,
                   weights = claims/1000)
summary(hm.mixed.3)
```

```{r}
round(fixef(hm.mixed.3) + t(as.matrix(ranef(hm.mixed.3)$state)), 2)
```

```{r}
#| echo: true

hm.dta$mu <- fitted(hm.mixed.3)
hm.dta$rPS <- resid(hm.mixed.3, 
                    type = "pearson", 
                    scaled = TRUE)
iqr <- tapply(hm.dta$rPS, hm.dta$state, 
              function(x) diff(quantile(x, c(0.25, 0.75))))
o.iqr <- order(iqr, decreasing = TRUE)
hm.dta$state.iqr <- fct_relevel(hm.dta$state,
                                levels(hm.dta$state)[o.iqr])
rm(iqr, o.iqr)
```
   
```{r}
#| echo: true
#| label: fig-hm-mixed-3-boxplot-within-residuals
#| fig-cap: "Boxplots and underlying data of standardized residuals for the `hm.mixed.3` model. The large blue circle is the average value of the residuals. The states have been ordered by the size of the interquartile range of their residuals."

ggplot(data = hm.dta,
       mapping = aes(x = rPS,
                     y = state.iqr)) +
  geom_vline(xintercept = 0, color = "gray") +
  geom_boxplot() +
  geom_jitter(height = 0.2,
              alpha = 0.3) +
  stat_summary(fun = mean,
               geom = "point", pch = 1,
               color = "blue", size = 2) +
  labs(x = "Standardized Pearson Residuals",
       y = "State")
```

```{r}
#| echo: true
#| message: false
#| label: fig-hm-mixed-3-diagnostic-plots
#| fig-cap: "Diagnostic plots for the `hm.mixed.3` model."

p1 <- ggplot(data = hm.dta,
       mapping = aes(x = mu,
                     y = rPS,
       color = state)) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "Std. Residuals") +
  theme(legend.position = "none")

p2 <- ggplot(data = hm.dta,
       mapping = aes(x = mu,
                     y = abs(rPS))) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Fitted Severity Values",
       y = "|Std. Residuals|") +
  theme(legend.position = "none")

p3 <- ggplot(data = hm.dta,
       mapping = aes(x = mu,
                     y = severity,
                     color = state)) +
  geom_abline(intercept = 0, slope = 1,
              color = "gray") +
  geom_point() +
  coord_cartesian(xlim = c(1000, 2500),
                  ylim = c(1000, 2500)) +
  labs(x = "Fitted Values",
       y = "Actual Values") +
  theme(legend.position = "none")

p4 <- ggplot(data = hm.dta,
       mapping = aes(sample = rPS)) +
  geom_qq() +
  geom_abline(slope = 1, intercept = 0) +
  labs(x = "Theoretical Quantiles",
       y = "Std. Residuals") +
  theme(legend.position = "none")

(p1 + p2) / (p3 + p4)
rm(list = ls(pattern = "p+"))
```

```{r}
#| include: false

tbl <- pivot_longer(ranef(hm.mixed.3)$state,
                    cols = 1:2,
                    names_to = "term",
                    values_to = "estimate")
ta <- filter(tbl, term == "(Intercept)") 
ta <- ta[order(ta$estimate),]
ta$f.val <- (1:5 - 0.5) / 5
ta$qn <- qnorm(ta$f.val)
tb <- filter(tbl, term == "ctime")
tb <- tb[order(tb$estimate),]
tb$f.val <- (1:5 - 0.5) / 5
tb$qn <- qnorm(ta$f.val)
tbl <- bind_cols(rep(1:5, each = 2),
                 bind_rows(ta, tb))
rm(ta,tb)
```

```{r}
#| echo: true
#| label: fig-hm-mixed-3-model-normal-plot-random-effects
#| fig-cap: "QQ-plots of the random effects for the Hachemeister `hm.mixed.3` model."

p1 <- ggplot(data = filter(tbl, term == "(Intercept)"),
             mapping = aes(x = estimate,
                           y = qn)) +
  geom_point() +
  labs(x = "Intercept Random Effects",
       y = "Std. Normal Quantiles")
p2 <- ggplot(data = filter(tbl, term == "ctime"),
             mapping = aes(x = estimate,
                           y = qn)) +
  geom_point() +
  labs(x = "ctime Random Effects",
       y = "Std. Normal Quantiles")
p1 + p2
rm(tbl, p1, p2)
```

```{r}
#| include: false

f <- function(r, sig.1 = 266.15, sig.2 = 21.13, N = 500) {
  n <- length(r)
  l <- letters[1:n]

  g <- function(rd) {
    x <- rd * sig.1 * seq(-1, 1, length = N)
    y.up <- sig.2 * sqrt(round(rd^2 - (x / sig.1)^2,
                               digits = 9))
    tb <- tibble(x = x, y.up = y.up, y.dn = -y.up)
    return(tb)
  }
  tbs <- map(as.list(r), g)
  tbs <- map2(tbs, as.list(l),
              ~ bind_cols("gp" = .y, .x))
  ans <- reduce(tbs, bind_rows)
  return(ans)
}
tbs <- f(c(1,2))
rm(f)
```

```{r}
#| echo: true
#| label: fig-hm-mixed-3-model-homogeneity-random-effects
#| fig-cap: "Scatter plot of estimated random effects for model `hm.mixed.3` along with contour lines that are 1 and 2 standard deviations away from the origin."

ggplot(data = tbs,
       mapping = aes(x = x,
                     group = gp)) +
  geom_line(mapping = aes(y = y.up), color = "gray") +
  geom_line(mapping = aes(y = y.dn), color = "gray") +
  geom_point(data = bind_cols(gp = "z",
                              ranef(hm.mixed.3)$state),
             mapping = aes(x = `(Intercept)`,
                           y = ctime,
                           gp = NULL)) +
  labs(x = "(Intercept)",
       y = "Centered Time")
rm(tbs)
```

```{r}
crit.points <- sqrt(qchisq(c(0.68, 0.95), df = 2))
names(crit.points) <- c("68%", "95%")
crit.points
```

```{r}
N <- 2000
mu <- c(0,0)
D <- matrix(c(70838, 0, 0, 446),
            nrow = 2, ncol = 2)
```

```{r}
set.seed(12837)
z <- rmvnorm(N, mean = mu, sigma = D)
```

```{r}
tb <- as.data.frame(z)
names(tb) <- c("x", "y")
tb$md <- apply(z, 1, function(z) sqrt(t(z - mu) %*% solve(D) %*% (z - mu)))
tb$md.bin.1 <- cut(tb$md, 
                   breaks = c(-Inf, 1, 2, Inf), 
                   labels = c("d < 1", "1 <= d < 2", "d >= 2"))
tb$md.bin.2 <- cut(tb$md,
                   breaks = c(-Inf, crit.points, Inf),
                   labels =c("d < 1.509", "1.509 <= d < 2.448", "d >= 2.448"))
```

```{r}
ggplot(data = tb,
       mapping = aes(x = x,
                     y = y,
                     color = md.bin.1)) +
  geom_point(alpha = 0.4) +
  labs(x = "Simulated Intercept Deviations",
       y = "Simulated Slope Deviations",
       color = "Distance")
```

```{r}
xtabs( ~ md.bin.1, data = tb) / N
```

```{r}
xtabs( ~ md.bin.2, data = tb) / N
```

```{r}
#| include: false

rm(N, mu, D, z, tb, crit.points)
rm(list = ls(pattern = "hm.*"))
```

