---
title: 'Practical Mixed Models for Actuaries'
subtitle: 'Code Chuncks Extracted via AWK script'
author: 'Ernesto Schirmacher'
output: html_notebook
temporary: in review (to be deleted)
---

## Chapter 2--GLM Review

```{r}
#| include: true
#| message: false

library(tidyverse)
library(patchwork)
library(kableExtra)
library(GLMsData)
library(statmod)
```

```{r}
#| include: true

data(lungcap, package = "GLMsData")
```

```{r}
#| echo: true
#| label: tbl-lungcap-numeric-summary-stats
#| tbl-cap: "Summary statistics for the numeric variables in the lung capacity data set.  Q1 is the first quartile, Q2 is the median, and Q3 is the third quartile."

stats <- rbind(summary(lungcap$FEV),
               summary(lungcap$Age),
               summary(lungcap$Ht))
dimnames(stats) <- list(c("FEV (in liters)", "Age (in years)", "Height (in inches)"),
                        c("Min", "Q1", "Q2", "Mean", "Q3", "Max"))
kbl(round(stats, 2),
    format = "pipe",
    booktabs = TRUE)
rm(stats)
```

```{r}
#| echo: true
#| message: false
#| label: fig-age-height-smoke-vs-fev
#| fig-cap: "Age and height versus forced expiratory volume. The red circles denote smoking subjects and the plus signs represent non-smoking subjects. The smooth trend curves, which ignore smoking status, suggest non-linear relationships with the response variable."

p <- ggplot(data = lungcap,
            mapping = aes(x = Age,
                          y = FEV))
p <- p + geom_jitter(data = lungcap[lungcap$Smoke == 0,],
                     width = 0.2, height = 0,
                     pch = 3)
p <- p + geom_jitter(data = lungcap[lungcap$Smoke == 1,],
                     width = 0.2, height = 0,
                     color = "red", alpha = 0.6)
p <- p + geom_smooth(data = lungcap,
                     se = FALSE)
p <- p + labs(x = "Age [jittered] (in years)",
              y = "FEV (in liters)")

q <- ggplot(data = lungcap,
            mapping = aes(x = Ht,
                          y = FEV))
q <- q + geom_point(data = lungcap[lungcap$Smoke == 0,],
                    pch = 3)
q <- q + geom_point(data = lungcap[lungcap$Smoke == 1,],
                    color = "red", alpha = 0.6)
q <- q + geom_smooth(se = FALSE)
q <- q + labs(x = "Height (in inches)",
              y = "FEV (in liters)")
p + q
```

```{r}
#| include: false

rm(p, q)
```

```{r}
n <- 7
bks <- c(min(lungcap$Ht) - 0.1,
         quantile(lungcap$Ht, probs = (1:(n-1))/n),
         max(lungcap$Ht) + 0.1)
lungcap <- lungcap %>%
  mutate(Ht.bin = cut(Ht,
                      breaks = bks))
```

```{r}
mv <- lungcap %>%
  group_by(Ht.bin) %>%
  summarize(sz = n(),
            mn = mean(FEV),
            vr = var(FEV))
```

```{r}
fm <- lm(log(vr) ~ log(mn),
         data = mv,
         weights = sz)
sfm <- summary(fm)
round(sfm$coef[,1:2], 3)
```

```{r}
#| include: false

rm(sfm, fm, mv, bks, n)
```

```{r}
n <- 20
bks <- c(min(lungcap$Ht) - 0.1,
         quantile(lungcap$Ht, probs = (1:(n-1))/n),
         max(lungcap$Ht) + 0.1)
lungcap <- lungcap %>%
  mutate(Ht.bin = cut(Ht,
                      breaks = bks))
```

```{r}
mv <- lungcap %>%
  group_by(Ht.bin) %>%
  summarize(sz = n(),
            mn = mean(FEV),
            vr = var(FEV))
```

```{r}
fm <- lm(log(vr) ~ log(mn),
         data = mv,
         weights = sz)
round(summary(fm)$coef[,1:2], 3)

rm(fm, mv, bks, n)
```

```{r}
#| echo: true
#| message: false
#| label: fig-age-height-smoke-vs-fev-arrows
#| fig-cap: "Age and height versus forced expiratory volume (`FEV`). The data has been rendered in muted gray and pink.  The arrows on both panels depict the variability of `FEV` for small, medium, and large values of `FEV`. The increase in variability is evident."

df <- tibble(x = c(5, 10, 15),
             y = c(0.8, 1.5, 2.2),
             xend = x,
             yend = c(2.1, 4.6, 5.8))
p <- ggplot(data = lungcap,
            mapping = aes(x = Age,
                          y = FEV)) +
  geom_jitter(data = lungcap[lungcap$Smoke == 0,],
              width = 0.2, height = 0,
              pch = 3,
              color = "gray") +
  geom_jitter(data = lungcap[lungcap$Smoke == 1,],
              width = 0.2, height = 0,
              color = "pink") +
  geom_segment(data = df,
               mapping = aes(x = x, y = y, 
                             xend = xend, yend = yend),
               color = "red",
               arrow = arrow(length = unit(2, "mm"),
                             ends = "both")) +
  labs(x = "Jittered Age (in years)",
       y = "FEV (in liters)")

df <- tibble(x = c(50, 60, 70),
             y = c(1.1, 1.6, 2.5),
             xend = x,
             yend = c(2.1, 3.2, 5.8))
q <- ggplot(data = lungcap,
            mapping = aes(x = Ht,
                          y = FEV)) +
  geom_point(data = lungcap[lungcap$Smoke == 0,],
             pch = 3,
             color = "gray") +
  geom_point(data = lungcap[lungcap$Smoke == 1,],
             color = "pink") +
  geom_segment(data = df,
               mapping = aes(x = x, y = y,
                             xend = xend, yend = yend),
               color = "red",
               arrow = arrow(length = unit(2, "mm"),
                             ends = "both")) +
  labs(x = "Height (in inches)",
       y = "FEV (in liters)")
p + q
rm(df, p, q)
```

```{r}
#| echo: true
#| label: tbl-gender-smoker-fev
#| tbl-cap: "Mean age, height, and forced expiratory volume (`FEV`) by gender and smoker status.  The number of observations (Obs.) in each cell are also given."

FS <- (lungcap$Gender == "F") & (lungcap$Smoke == 1)
FN <- (lungcap$Gender == "F") & (lungcap$Smoke == 0)
MS <- (lungcap$Gender == "M") & (lungcap$Smoke == 1)
MN <- (lungcap$Gender == "M") & (lungcap$Smoke == 0)
tb <- tibble(Gender = c("Female", "Male"),
             sz.NS = c(sum(FN), sum(MN)),
             mn.Age.NS = c(mean(lungcap$Age[FN]),
                           mean(lungcap$Age[MN])),
             mn.Ht.NS = c(mean(lungcap$Ht[FN]),
                          mean(lungcap$Ht[MN])),
             mn.FEV.NS = c(mean(lungcap$FEV[FN]),
                           mean(lungcap$FEV[MN])),
             sz.S =  c(sum(FS), sum(MS)),
             mn.Age.S = c(mean(lungcap$Age[FS]),
                          mean(lungcap$Age[MS])),
             mn.Ht.S = c(mean(lungcap$Ht[FS]),
                         mean(lungcap$Ht[MS])),
             mn.FEV.S = c(mean(lungcap$FEV[FS]),
                          mean(lungcap$FEV[MS])))
kbl(tb,
    row.names = FALSE,
    col.names = c("Gender", 
                  "Obs.", "Age", "Height", "FEV", 
                  "Obs.", "Age", "Height", "FEV"),
    digits = c(0, 0, 1, 1, 2, 0, 1, 1, 2),
    booktabs = TRUE) %>%
  add_header_above(c(" " = 1, " " = 1, "Mean" = 3,
                     " " = 1, " Mean" = 3)) %>%
  add_header_above(c(" " = 1, "Non-Smoker" = 4, "Smoker" = 4))

rm(FS, MS, FN, MN, tb)
```

```{r}
ols.fit <- glm(FEV ~ Ht,
               data = lungcap,
               family = gaussian(link = "identity"))
lungcap <- lungcap %>%
  mutate(olsfit.mu = predict(ols.fit, type = "response"),
         olsfit.rD = resid(ols.fit, type = "deviance"))
```

```{r}
#| echo: true
#| message: false
#| label: fig-gaussian-fev-ht-residuals-and-abs
#| fig-cap: "Fitted values versus deviance residuals for an ordinary least squares model for forced expiratory volume that includes height as an explanatory variable. Note the strong pattern in both panels telling us that our model is not adequate."

p <- ggplot(data = lungcap,
            mapping = aes(x = olsfit.mu,
                          y = olsfit.rD)) +
  geom_point() +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "Residuals")
q <- ggplot(data = lungcap,
            mapping = aes(x = olsfit.mu,
                          y = abs(olsfit.rD))) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "Abs. Value of Residuals")
p + q
rm(p, q)
```

```{r}
gi.H.fit <- glm(FEV ~ Ht,
                data = lungcap,
                family = Gamma(link = "identity"))
(sgi.H.fit <- summary(gi.H.fit))
```

```{r}
#| include: true

set.seed(19390349)
n <- nrow(lungcap)
disp <- sgi.H.fit$dispersion
lungcap <- lungcap %>%
  mutate(giHfit.mu = predict(gi.H.fit, type = "response"),
         giHfit.rp1 = rgamma(n,
                             shape = 1/disp,
                             scale = giHfit.mu * disp),
         giHfit.rp2 = rgamma(n,
                             shape = 1/disp,
                             scale = giHfit.mu * disp),
         giHfit.rp3 = rgamma(n,
                             shape = 1/disp,
                             scale = giHfit.mu * disp))
rm(n,disp)
```

```{r}
#| echo: true
#| message: false
#| label: fig-fake-data-gamma-identity-fev-ht
#| fig-cap: "One panel contains the actual data and the other panels have simulated data from a fitted model.  Can you identify the panel with the actual data?"
p <- ggplot(data = lungcap,
            mapping = aes(x = Ht)) + ylim(0,6) +
  labs(x = "Height (in inches)",
       y = "FEV (in liters)")
p1 <- p + geom_point(mapping = aes(y = giHfit.rp3),
                     alpha = 0.2)
p2 <- p + geom_point(mapping = aes(y = FEV),
                     alpha = 0.2)
p3 <- p + geom_point(mapping = aes(y = giHfit.rp1),
                     alpha = 0.2)
p4 <- p + geom_point(mapping = aes(y = giHfit.rp2),
                     alpha = 0.2)
(p1 + p2) / (p3 + p4)
rm(list = ls(pattern = "^p"))
```

```{r}
#| message: false

p <- ggplot(data = lungcap,
            mapping = aes(x = Ht)) + ylim(0,6) +
  labs(x = "Height (in inches)",
       y = "FEV (in liters)")
p1 <- p + geom_point(mapping = aes(y = giHfit.rp3),
                     alpha = 0.2) + 
  geom_smooth(aes(y = giHfit.rp3),
              se = FALSE)
p2 <- p + geom_point(mapping = aes(y = FEV),
                     alpha = 0.2) + 
  geom_smooth(aes(y = FEV),
              se = FALSE)
p3 <- p + geom_point(mapping = aes(y = giHfit.rp1),
                     alpha = 0.2) + 
  geom_smooth(aes(y = giHfit.rp1),
              se = FALSE)
p4 <- p + geom_point(mapping = aes(y = giHfit.rp2),
                     alpha = 0.2) + 
  geom_smooth(aes(y = giHfit.rp2),
              se = FALSE)
(p1 + p2) / (p3 + p4)
rm(list = ls(pattern = "^p"))
```

```{r}
lungcap$Ht.sq <- lungcap$Ht^2
gi.H2.fit <- glm(FEV ~ Ht + Ht.sq,
                 data = lungcap,
                 family = Gamma(link = "identity"))
gl.H.fit <- glm(FEV ~ Ht,
                data = lungcap,
                family = Gamma(link = "log"))
```

```{r}
round(coef(gi.H2.fit), 5)
```

```{r}
round(coef(gl.H.fit), 4)
```
Thus we can infer that as the height for a child
increases by one inch, their forced expiratory volume
will increase by approximately 5.4% $(e^{0.0522} - 1)$.

```{r}
#| echo: true

lungcap <- lungcap %>%
  mutate(giH2fit.mu = predict(gi.H2.fit, type = "response"),
         giH2fit.eta = predict(gi.H2.fit, type = "link"),
         giH2fit.rW = resid(gi.H2.fit, type = "working"),
         giH2fit.wR = giH2fit.eta + giH2fit.rW,
         giH2fit.rD = resid(gi.H2.fit, type = "deviance"),
         giH2fit.rQ = qresid(gi.H2.fit))
```

```{r}
#| echo: true

lungcap <- lungcap %>%
  mutate(glHfit.mu = predict(gl.H.fit, type = "response"),
         glHfit.eta = predict(gl.H.fit, type = "link"),
         glHfit.rW = resid(gl.H.fit, type = "working"),
         glHfit.wR = glHfit.eta + glHfit.rW,
         glHfit.rD = resid(gl.H.fit, type = "deviance"),
         glHfit.rQ = qresid(gl.H.fit))
```

```{r}
#| echo: true
#| label: fig-quadratic-log-link-gamma-fev-height-diagnostics
#| fig-cap: "Fitted values versus quantile residuals and working response versus linear predictor for the quadratic as well as the log-link model. All four plots display the desired null pattern and in the top panels we may have two outlying observations (residuals below the horizontal line at $y = -4$)."

p1 <- ggplot(data = lungcap,
             mapping = aes(x = giH2fit.mu,
                           y = giH2fit.rQ)) +
  geom_point() +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "Quantile Residuals",
       title = "Quadratic Model")

p2 <- ggplot(data = lungcap,
             mapping = aes(x = glHfit.mu,
                           y = glHfit.rQ)) +
  geom_point() +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "Quantile Residuals",
       title = "Log-link Model")

p3 <- ggplot(data = lungcap,
             mapping = aes(x = giH2fit.wR,
                           y = giH2fit.eta)) +
  geom_point() + geom_abline(intercept = 0,
                             slope = 1,
                             color = "red") +
  labs(x = "Working Response",
       y = "Linear Predictor")

p4 <- ggplot(data = lungcap,
             mapping = aes(x = glHfit.wR,
                           y = glHfit.eta)) +
  geom_point() + geom_abline(intercept = 0,
                             slope = 1,
                             color = "red") +
  labs(x = "Working Response",
       y = "Linear Predictor")

(p1 + p2)/(p3 + p4)
rm(list = ls(pattern = "p[1-4]"))
```

```{r}
#| message: false
#| warning: false
p1 <- ggplot(data = lungcap,
             mapping = aes(x = Ht,
                           y = giH2fit.rQ)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Height (in inches)",
       y = "Quantile Residuals",
       title = "Quadratic Model")
p2 <- ggplot(data = lungcap,
             mapping = aes(x = Ht,
                           y = glHfit.rQ)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Height (in inches)",
       y = "Quantile Residuals",
       title = "Log-link Model")

p1 + p2
rm(p1, p2)
```

```{r}
gl.HGS.fit <- glm(FEV ~ Smoke + Gender + Ht,
                  data = lungcap,
                  family = Gamma(link = "log"))
sgl.HGS.fit <- summary(gl.HGS.fit)
round(coef(sgl.HGS.fit), 4)
```

```{r}
#| include: true

lungcap <- lungcap %>%
  mutate(glHGSfit.mu = predict(gl.HGS.fit, type = "response"),
         glHGSfit.eta = predict(gl.HGS.fit, type = "link"),
         glHGSfit.rW = resid(gl.HGS.fit, type = "working"),
         glHGSfit.wR = glHGSfit.eta + glHGSfit.rW,
         glHGSfit.rD = resid(gl.HGS.fit, type = "deviance"),
         glHGSfit.rQ = qresid(gl.HGS.fit))
```

```{r}
#| echo: true
#| message: false
#| warning: false
#| label: fig-lungcap-final-model-diagnostics
#| fig-cap: "Diagnostic plots for our final model. The two left-hand panels show a random cloud of points centered about the line $y = 0$.  The trend line exhibits a small positive bump in the center of the display. The upper right-hand panel shows that our model captures the increasing variablity in the response variable well. The QQ-plot on the lower right-hand panel shows that lower tail of our data is thicker than it should be."
#| fig-width: 6
#| fig-height: 7

p1 <- ggplot(data = lungcap,
             mapping = aes(x = glHGSfit.mu,
                           y = glHGSfit.rQ)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "Quantile Residuals")
p2 <- ggplot(data = lungcap,
             mapping = aes(x = glHGSfit.mu,
                           y = abs(glHGSfit.rQ))) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Fitted Values, FEV (in liters)",
       y = "|Quantile Residuals|")
p3 <- ggplot(data = lungcap,
             mapping = aes(x = Ht,
                           y = glHGSfit.rQ)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Height (in inches)",
       y = "Quantile Residuals")
p4 <- ggplot(data = lungcap,
             mapping = aes(sample = glHGSfit.rQ)) +
  stat_qq() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(x = "Theoretical Quantiles",
       y = "Sample Quantiles")
p5 <- ggplot(data = lungcap,
             mapping = aes(x = Gender,
                           y = glHGSfit.rQ)) +
  geom_boxplot() +
  labs(x = "Gender",
       y = "Quantile Residuals") +
  scale_x_discrete(labels = c("Female", "Male"))
p6 <- ggplot(data = lungcap,
             mapping = aes(x = factor(Smoke),
                           y = glHGSfit.rQ)) +
  geom_boxplot() +
  labs(x = "Smoking Status",
       y = "Quantile Residuals") +
  scale_x_discrete(labels = c("No", "Yes"))
(p1 + p2) / (p3 + p5) / (p6 + p4)
rm(list = ls(pattern = "^p"))
```

```{r}
#| echo: true

p1 <- ggplot(data = lungcap,
             mapping = aes(x = as.factor(Smoke),
                           y = glHGSfit.rQ)) +
  geom_boxplot() +
  stat_summary(fun = mean,
               geom = "point",
               color = "red") +
  labs(x = "Smoke Indicator",
       y = "Quantile Residuals") +
  scale_x_discrete(labels = c("No", "Yes"))
p2 <- ggplot(data = lungcap,
             mapping = aes(x = as.factor(Gender),
                           y = glHGSfit.rQ)) +
  geom_boxplot() +
  stat_summary(fun = mean, geom = "point", color = "red") +
  labs(x = "Gender",
       y = "Quantile Residuals") +
  scale_x_discrete(labels = c("Female", "Male"))
p1 + p2
rm(p1, p2)
```

