---
title: 'Practical Mixed Models for Actuaries'
subtitle: 'Code Chuncks Extracted via AWK script'
author: 'Ernesto Schirmacher'
output: html_notebook
temporary: in review (to be deleted)
---

## Chapter 5--Generalized Linear Mixed Models

```{r}
#| include: false
#| label: load-libraries

library(tidyverse)
library(patchwork)
library(statmod)
library(lme4)
library(hglm)
library(dhglm)
library(kableExtra)
library(GGally)
```

```{r}
#| label: load-hachemeister-data-and-compute-ctime

hm.dta <- read_csv("hachemeister-data.csv",
                   col_types = "fidd")
CG <- with(hm.dta,
           tapply(time * claims, state, sum) / 
             tapply(claims, state, sum))
hm.dta$ctime <- hm.dta$time - CG[hm.dta$state]
rm(CG)
```

```{r}
#| label: fit-HGLM-for-hachemeister-data

hm.hglm.3 <- hglm2(severity ~ ctime + (1 | state) + (0 + ctime | state),
                   data = hm.dta,
                   family = gaussian(link = "identity"),
                   rand.family = gaussian(link = "identity"),
                   weights = claims)
```

```{r}
#| label: HGLM-hachemeister-summary-output

summary(hm.hglm.3)
```

```{r}
#| include: false
#| label: fit-GLMM-hachemeister-data

hm.mixed.3 <- lmer(severity ~ ctime + (1 | state) + (0 + ctime | state),
                   data = hm.dta,
                   weights = claims / 1000)
```

```{r}
#| label: assemble-HGLM-coefficients

ans <- hm.hglm.3$fixef + matrix(hm.hglm.3$ranef, nrow = 2, ncol = 5, byrow = TRUE)
dimnames(ans) <- list(c("(Intercept)", "ctime"),
                      1:5)
round(ans, 3)
```

```{r}
#| label: assemble-GLMM-coefficients

round(fixef(hm.mixed.3) + t(as.matrix(ranef(hm.mixed.3)$state)), 3)
```

```{r}
#| include: false
#| label: clean-up-hachemeister-example

rm(ans, weights, hm.mixed.3, hm.hglm.3, hm.dta)
```

```{r}
#| include: false
#| label: load-fabric-data-compute-log-roll-length

data(fabric, package = "mdhglm")
fabric$x.lg <- log(fabric$x)
```

```{r}
#| echo: true
#| label: fig-fabric-length-vs-faults
#| fig-cap: "Number of faults in a roll of fabric."

ggplot(data = fabric,
       mapping = aes(x = x,
                     y = y)) +
  geom_point() +
  labs(x = "Length of Roll (in m)",
       y = "Number of Faults")
```

```{r}
#| label: fabric-roll-length-vs-faults-log-scales

ggplot(data = fabric,
       mapping = aes(x = log(x),
                     y = log(y))) +
  geom_point() +
  labs(x = "Length of Roll (log-scale)",
       y = "Number of Faults (log-scale)")
```

```{r}
#| echo: true
#| label: fabric-glm-poisson-model

fab.poi.glm <- glm(y ~ x.lg,
                   data = fabric,
                   family = poisson(link = "log"))
summary(fab.poi.glm)
```

```{r}
#| echo: true
#| label: fabric-glm-neg-binomial-model

fab.nb.glm <- glm.nb(y ~ x.lg,
                     data = fabric)
summary(fab.nb.glm)
```

```{r}
#| label: compute-diagnostic-measures-for-neg-binomial-model

fabric.res <- fabric |>
  mutate(eta = predict(fab.nb.glm, type = "link"),
         mu  = predict(fab.nb.glm, type = "response"),
         rQ  = qresid(fab.nb.glm),
         rW  = resid(fab.nb.glm, type = "working"),
         wR  = rW + eta)
```

```{r}
#| label: compute-diagnostic-plots-neg-binomial-model

p1 <- ggplot(data = fabric.res,
             mapping = aes(x = mu,
                           y = rQ)) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "Quantile Residuals")
p2 <- ggplot(data = fabric.res,
             mapping = aes(x = mu,
                           y = abs(rQ))) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "Abs(Quantile Residuals)")
p3 <- ggplot(data = fabric.res,
             mapping = aes(x = x.lg,
                           y = rQ)) +
  geom_point() +
  labs(x = "Length of Fabric Roll (log-scale)",
       y = "Quantile Residuals")
p4 <- ggplot(data = fabric.res,
             mapping = aes(x = wR,
                           y = eta)) +
  geom_point() + 
  labs(x = "Working Response",
       y = "Linear Predictor")
```

```{r}
#| label: arrange-neg-binomial-diagnostic-plots

(p1 + p2) / (p3 + p4)
```

```{r}
#| include: false
rm(fabric.res, p1, p2, p3, p4)
```

```{r}
#| echo: true
#| label: fig-density-for-neg-binomial-random-effect
#| fig-cap: "The density function for the random effect $u$."

ggplot(data = tibble(x = seq(0.1, 2.2, length = 500),
                     y = dgamma(x, shape = 8.67, scale = 1/8.67)),
       mapping = aes(x = x,
                     y = y)) +
  geom_line() +
  labs(x = "Unobserved Random Variable",
       y = "Density")
```

```{r}
#| label: fabric-dhglm-mean-model

model.mu <- DHGLMMODELING(Model = "mean",
                          Link = "log",
                          LinPred = y ~ x.lg + (1 | rf),
                          RandDist = "gamma")
```

```{r}
#| label: fabric-dhglm-dispersion-model

model.phi <- DHGLMMODELING(Model = "dispersion")
```

```{r}
#| label: fabric-dhglm-model-fitting

fab.hglm.nb <- dhglmfit(RespDist = "poisson",
                        DataMain = fabric,
                        MeanModel = model.mu,
                        DispersionModel = model.phi)
```

```{r}
#| include: false

rm(model_mu, model_phi)
```

```{r}
#| echo: true
#| label: compute-diagnostic-plots-for-hglm-model

df <- tibble(mu = as.numeric(fab.hglm.nb[["mu"]]),
             srD = as.numeric(fab.hglm.nb[["mean_residual"]]))
p1 <- ggplot(data = df,
             mapping = aes(x = mu,
                           y = srD)) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "Stu. Dev. Residuals")
p2 <- ggplot(data = df,
             mapping = aes(x = mu,
                           y = abs(srD))) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "|Stu. Dev. Residuals|")
p3 <- ggplot(data = df,
             mapping = aes(sample = srD)) +
  geom_qq() +
  labs(x = "Theoretical Quantiles",
       y = "Sample Quantiles")
p4 <- ggplot(data = df,
             mapping = aes(srD)) +
  geom_histogram(bins = 5) +
  labs(x = "Stu. Dev. Residuals",
       y = "Frequency")
```

```{r}
#| echo: true
#| label: fig-fabric-diagnostic-plots-hglm-model
#| fig-cap: "Diagnostic plots from a Poisson-gamma hierarchical generalized linear model fitted to the fabric data. The top panels show that the model has some deficiencies beacuase there are discernible patterns.  The bottom panels show the expected patterns."

(p1 + p2) / (p3 + p4)
```

```{r}
#| include: false
#| label: clean-up-fabric-example

rm(list = ls(pattern = "p[1-4]"))
rm(fabric, fab.poi.glm, fab.nb.glm, fab.hglm.nb, df)
```

```{r}
#| include: false
#| label: load-train-dataset

data(train, package = "mdhglm")
```

```{r}
#| echo: true
#| label: fig-train-log-rate-vs-time
#| fig-cap: "The rate of collisions, per million kilometers traveled (log-scale), between British passenger trains and road vehicles from 1975 to 2003."

ggplot(data = train,
       mapping = aes(x = x + 1975,
                     y = log(y/t))) +
  geom_point() + 
  labs(x = "Calendar Year",
       y = "Rate of Collission (per M km, log-scale)")
```

```{r}
#| label: train-poi-model

train.poi <- glm(y ~ x + offset(log(t)),
                 data = train,
                 family = poisson(link = "log"))
summary(train.poi)
```

```{r}
#| label: train-poi-model-diagnostic

ggplot(data = tibble(mu = predict(train.poi, type = "response"),
                     rD = resid(train.poi, type = "deviance")),
       mapping = aes(x = (mu),
                     y = abs(rD))) +
  geom_point() +
  labs(x = "Fitted Values",
       y = "abs(Deviance Residuals)")
```

```{r}
#| label: train-hglm-model-specification-and-fitting

model_mu <- DHGLMMODELING(Model = "mean",
                      Link = "log",
                      LinPred = y ~ x + (1 | id),
                      Offset = log(train$t),
                      RandDist = "gamma")
model_phi <- DHGLMMODELING(Model = "dispersion")
train.hglm <- dhglmfit(RespDist = "poisson",
                       DataMain = train,
                       MeanModel = model_mu,
                       DispersionModel = model_phi)
```

```{r}
#| include: false

rm(model_mu, model_phi)
```

```{r}
#| echo: true
#| label: compute-var-parameter-and-grab-estimate-random-effects

theta <- exp(train.hglm[["lambda_coeff"]][1])
df <- tibble(x = train.hglm[["v_h"]][,1],
             y = 0)
```

```{r}
#| echo: true
#| label: fig-train-random-effects-estimated-density
#| fig-cap: "Estimated density function for train dataset along with the estimated random effects (points on the $x$-axis)."

ggplot(data = tibble(x = seq(0.01, 2.5, length = 200),
                     y = dgamma(x, scale = theta, shape = 1/theta)),
       mapping = aes(x = x,
                     y = y)) +
  geom_line() +
  geom_point(data = df,
             mapping = aes(x = exp(x),
                           y = y)) +
  labs(x = "Unobservable Random Effect",
       y = "Density")
```

```{r}
#| include: false

rm(theta, df)
```

```{r}
#| echo: true
#| label: compute-studentized-deviance-residuals-for-train-models

df <- tibble(model = factor(rep(c("Poisson Model", "HGLM Model"), each = 29),
                            levels = c("Poisson Model", "HGLM Model")),
             value = NA)
df$value[1:29] <- rstudent(train.poi)
df$value[30:58] <- train.hglm[["mean_residual"]][,1]
```

```{r}
#| echo: true
#| label: fig-train-QQ-plots-poisson-hglm
#| fig-cap: "Quantile-quantile plot for the studentized deviance residuals from the Poisson and the Poisson-gamma (HGLM) models."

ggplot(data = df,
       mapping = aes(sample = value)) +
  facet_wrap(vars(model)) +
  geom_qq(aes()) + geom_qq_line() +
  labs(x = "Theoretical Quantiles",
       y = "Sample Quantiles")
```

```{r}
#| include: false
#| label: clean-up-train-example

rm(df)
rm(train, train.hglm, train.poi)
```

```{r}
#| include: false
#| label: load-diabetes-data

data(diabetes, package = "lars")
diab <- tibble(age = as.numeric(diabetes[,1][, 1]),
               sex = as.numeric(diabetes[,1][, 2]),
               bmi = as.numeric(diabetes[,1][, 3]),
               abp = as.numeric(diabetes[,1][, 4]),
               tc  = as.numeric(diabetes[,1][, 5]),
               ldl = as.numeric(diabetes[,1][, 6]),
               hdl = as.numeric(diabetes[,1][, 7]),
               tch = as.numeric(diabetes[,1][, 8]),
               ltg = as.numeric(diabetes[,1][, 9]),
               glu = as.numeric(diabetes[,1][,10]),
               y   = as.numeric(diabetes[,2]))
rm(diabetes)
```

```{r}
#| include: false
#| label: first-6-rows-of-table-1-from-efronLeastAngleRegression2004

tb <- tibble(patient = 1:6,
             age = c(59, 48, 72, 24, 50, 23),
             sex = c(2, 1, 2, 1, 1, 1),
             bmi = c(32.1, 21.6, 30.5, 25.3, 23.0, 22.6),
             abp = c(101, 87, 93, 84, 101, 89),
             tc  = c(157, 183, 156, 198, 192, 139),
             ldl = c(93.2, 103.2, 93.6, 131.4, 125.4, 64.8),
             hdl = c(38, 70, 41, 40, 52, 61),
             tch = c(4, 3, 4, 5, 4, 2),
             ltg = c(4.9, 3.9, 4.7, 4.9, 4.3, 4.2),
             glu = c(87, 69, 85, 89, 80, 68),
             y   = c(151, 75, 141, 206, 135, 97))
```

```{r}
#| echo: true
#| label: tbl-first-six-rows-from-table-1-in-efronLeastAngleRegression2004
#| tbl-cap: "First six rows of diabetes data."

tb |>
  kbl(booktabs = TRUE,
      align = "crrrrrrrrrrr",
      col.names = c("Patient", "age", "sex", "bmi", "abp", "tc",
                    "ldl", "hdl", "tch", "ltg", "glu", "y"),
      linesep = c("", "", "\\addlinespace")) |>
  add_header_above(c(" " = 1, " " = 1, " " = 1, " " = 1, " " = 1,
                     "Serum measurements" =  6, "Response" = 1),
                   align = c("c", "r", "r", "r", "r", "c", "r")) |>
  kable_styling(latex_options = "scale_down") |>
  add_footnote(label = "Table 1 in (Efron et al. 2004).",
               notation = "none") |>
  kable_classic()
rm(tb)
```

```{r}
#| echo: true
#| label: compute-diabetes-exploratory-graphs

p1 <- ggplot(data = diab,
             mapping = aes(x = age,
                           y = y)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Values of Age",
       y = "Disease Progression")

p2 <- ggplot(data = diab,
             mapping = aes(x = bmi,
                           y = y)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Values of BMI",
       y = "Disease Progression")

p3 <- ggplot(data = diab,
             mapping = aes(x = hdl,
                           y = y)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Values of HDL",
       y = "Disease Progression")

p4 <- ggplot(data = diab,
             mapping = aes(x = glu,
                           y = y)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Values of Glucose",
       y = "Disease Progression")
```

```{r}
#| echo: true
#| label: fig-diabetes-exploratory-graphs
#| message: false
#| fig-cap: "Exploratory graphs of disease progression versus explanatory variables age, body mass index (BMI), high density lipoprotein (HDL), and glucose. A scatterplot smooth has been added to aid in detecting the overall pattern. Note that in several of the panels, the variance in disease progression is not constant across the values of the explanatory variables."

(p1 + p2) / (p3 + p4)
rm(p1, p2, p3, p4)
```

```{r}
#| echo: true
#| label: fig-diabetes-serum-variables-pairs-plot
#| fig-cap: "Scatterplot matrix for the blood serum variables. The diagonal entries show non-parametric estimates of the density function for each variable. The upper triangular entries are the pairwise linear correlation coefficents and the bottom triangular entries are the pairwise scatterplot for the variables."

ggpairs(diab[,5:10],
        axisLabels = "none",
        progress = FALSE)
```

```{r}
#| label: diabetes-joint-full-model-structure

model.mu <-  DHGLMMODELING(Model = "mean",
                           Link = "identity",
                           LinPred = y ~ age + sex + bmi + abp + tc + 
                             ldl + hdl + tch + ltg + glu)

model.phi <- DHGLMMODELING(Model = "dispersion",
                           Link = "log",
                           LinPred = y ~ age + sex + bmi + abp + tc + 
                             ldl + hdl + tch + ltg + glu)
```

```{r}
#| label: fit-diabetes-joint-full-model

diab.model <- dhglmfit(RespDist = "gaussian",
                       DataMain = diab,
                       MeanModel = model.mu,
                       DispersionModel = model.phi)
```

```{r}
#| include: false
#| label: clean-up-model-specs

rm(model.mu, model.phi)
```

```{r}
#| label: fit-diabetes-final-joint-model

model.mu <- DHGLMMODELING(Model = "mean",
                          Link = "identity",
                          LinPred = y ~ sex + bmi + abp + ltg)
model.phi <- DHGLMMODELING(Model = "dispersion",
                           Link = "log",
                           LinPred = y ~ sex + abp)
diab.final <- dhglmfit(RespDist = "gaussian",
                       DataMain = diab,
                       MeanModel = model.mu,
                       DispersionModel = model.phi)
```

```{r}
#| include: false
#| label: clean-up-final-model-specs

rm(model.mu, model.phi)
```

```{r}
#| include: false
#| label: compute-diabetes-small-model-fitted-values-and-residuals

diab.sm <- diab |>
  mutate(mean.mu = diab.final[7][[1]],
         mean.sr = diab.final[1][[1]],
         phi.mu =  diab.final[4][[1]],
         phi.sr =  diab.final[3][[1]])
```

```{r}
#| echo: true
#| label: fig-diabetes-final-model-fitted-vs-residuals-mean-and-dispersion-model
#| message: false
#| fig-cap: ""

p1 <- ggplot(data = diab.sm,
       mapping = aes(x = mean.mu,
                     y = mean.sr)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Fitted Values",
       y = "Studentized Residuals",
       title = "Mean Model")
p2 <- ggplot(data = diab.sm,
       mapping = aes(x = phi.mu,
                     y = phi.sr)) +
  geom_point() + geom_smooth(se = FALSE) +
  labs(x = "Scaled Fitted Values",
       y = "Studentized Residuals",
       title = "Dispersion Model")
p1 + p2
```

```{r}
#| include: false
#| label: clean-up-environment

rm(list = ls(pattern = "diab"))
rm(p1, p2)
```

